# Generated by Django 3.1 on 2020-08-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionize_id', models.PositiveIntegerField(verbose_name='SessionizeにおけるID')),
                ('day', models.PositiveIntegerField(verbose_name='トークする日（◯日目）')),
                ('no', models.PositiveIntegerField(verbose_name='トーク時間帯の番号')),
                ('room', models.CharField(choices=[('#pyconjp', 'Pyconjp'), ('#pyconjp_1', 'Pyconjp 1'), ('#pyconjp_2', 'Pyconjp 2'), ('#pyconjp_3', 'Pyconjp 3'), ('#pyconjp_4', 'Pyconjp 4'), ('#pyconjp_5', 'Pyconjp 5')], max_length=10, verbose_name='トークのトラック')),
                ('title', models.CharField(max_length=100, verbose_name='トークのタイトル')),
                ('description', models.TextField(verbose_name='詳細（タイムライン）')),
                ('elevator_pitch', models.TextField(verbose_name='概要（エレベータピッチ）')),
                ('talk_format', models.CharField(choices=[('Talk(45min)', 'Talk 45Min'), ('Talk(30min)', 'Talk 30Min'), ('Talk(15min)', 'Talk 15Min'), ('Hands-on session(45min)', 'Handson Session')], max_length=23, verbose_name='トークの持ち時間')),
                ('category', models.CharField(choices=[('Python core', 'Python Core'), ('Tips of development with Python', 'Tips Python Development'), ('Web programming (including web frameworks)', 'Web Programming'), ('Data Science / Machine Learning', 'Data And Ml'), ('System administration', 'System Administration'), ('Case studies (excluding web programming or machine learning)', 'Case Studies'), ('Embedding python in hardware', 'Embedding'), ('GUI and games', 'Gui Games'), ('Network programming', 'Network Programming'), ('Fintech', 'Fintech'), ('Python in education', 'Education'), ('Community building related to Python', 'Community'), ('Anything else basically which doesn’t fall into the types of topics above', 'Others')], max_length=73, verbose_name='トークのカテゴリ')),
                ('audience_python_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=12, verbose_name='聴衆に求めるPythonのレベル')),
                ('audience_domain_expertise', models.CharField(choices=[('0%', 'Novice'), ('50%', 'Practitioner'), ('100%', 'Professional')], max_length=4, verbose_name='聴衆に求めるトークの分野の知識レベル')),
                ('speaking_language', models.CharField(choices=[('ja', 'Japanese'), ('en', 'English')], max_length=2, verbose_name='発表の言語')),
                ('slide_language', models.CharField(choices=[('ja', 'Japanese only'), ('en', 'English only'), ('bo', 'Both')], max_length=2, verbose_name='スライドの言語')),
                ('prerequisite_knowledge', models.TextField(verbose_name='聴衆に求める前提知識')),
                ('audience_take_away', models.TextField(verbose_name='聴衆が持ち帰ることができるもの')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
